package com.videoClub.rules.cepPurchase

import com.videoClub.event.*;
import com.videoClub.model.*;


rule "More than 10 purchases in 1 hour from same user"
    when
        $t1: PurchaseEvent($userId: user.id, $user : user)
        Number(intValue>=10 ) from accumulate(
			$p: PurchaseEvent(user.id == $userId)
			over window:time(1h), count($p)
		)
    then
    	$user.setAllowedToPurchase(false);
end


rule "No suspicious user event and less than 10 purchase events in 1 hour"
    when
        $t1: PurchaseEvent($userId: user.id, $user : user)
        Number(intValue<10 ) from accumulate(
			$p: PurchaseEvent(user.id == $userId)
			over window:time(1h), count($p)
		)
    then
    	$user.setAllowedToPurchase(true);
end