//created on: May 30, 2020
package com.videoClub.rules.adminRecommendation

import com.videoClub.dto.MessageDto;

global Integer usersNumber;



query actorsRateIsRelevant()
	// veci je broj ArtistRateBadge objekata koji se odnose na listu glumaca filma
	// nego ukupan unwatchedNumber svih ArtistReviewBadge objekata koji se odnose na listu glumaca filma
end

query highlyRatedActors()
	actorsRateIsRelevant();
	// prosek svih averageRate u ArtistRateBadge objektima koji se odnose na listu glumaca filma
	// je veci ili jednak 4
end

query watchedActors()
	highlyRatedActors();
	// gleda se watchedNumber i unwatchedNumber svih ArtistReviewBadge u radnoj memoriji
	// koji se odnose na listu glumaca filma
	// watchedNumber mora biti veci od unwatchedNumber
end

query popularActors()
	watchedActors();
	// sabiraju se svi ArtistReviewBadge objekti koji se odnose na listu glumaca iz filma
	// da bi se uslov zadovoljio, mora biti barem 50% ArtistReviewBadge objekata od ukupnog
	// broja korisnika (ukupan broj korisnika predstavljen globalnom prom)
	// posmatraju se SAMO registrovani korisnici
	// postaviti globalnu promeljivu pri inicijalizaciji sesije (velicina liste svih reg korisnika)
end

query goodActors()
	popularActors();
end

//===============================================================================================

query scenaristRateIsRelevant()
	// veci je broj ArtistRateBadge objekata koji se odnose na writtenBy filma
	// nego ukupan unwatchedNumber svih ArtistReviewBadge objekata koji se odnose na writtenBy filma
end

query highlyRatedScenarist()
	scenaristRateIsRelevant();
	// prosek svih averageRate u ArtistRateBadge objektima koji se odnose na writtenBy filma
	// je veci ili jednak 4
end

query watchedScenarist()
	highlyRatedScenarist();
	// gleda se watchedNumber i unwatchedNumber svih ArtistReviewBadge u radnoj memoriji
	// koji se odnose na writtenBy filma
	// watchedNumber mora biti veci od unwatchedNumber
end

query popularScenarist()
	watchedScenarist();
	// sabiraju se svi ArtistReviewBadge objekti koji se odnose na writtenBy filma
	// da bi se uslov zadovoljio, mora biti barem 50% ArtistReviewBadge objekata od ukupnog
	// broja korisnika (ukupan broj korisnika predstavljen globalnom prom)
	// posmatraju se SAMO registrovani korisnici
	// postaviti globalnu promeljivu pri inicijalizaciji sesije (velicina liste svih reg korisnika)
end

query goodScenarist()
	popularScenarist();
end

//===============================================================================================

query directorRateIsRelevant()
	// veci je broj ArtistRateBadge objekata koji se odnose na rezisera filma
	// nego ukupan unwatchedNumber svih ArtistReviewBadge objekata koji se odnose na rezisera filma
end

query highlyRatedDirector()
	directorRateIsRelevant();
	// prosek svih averageRate u ArtistRateBadge objektima koji se odnose na rezisera filma
	// je veci ili jednak 4
end

query watchedDirector()
	highlyRatedDirector();
	// gleda se watchedNumber i unwatchedNumber svih ArtistReviewBadge u radnoj memoriji
	// koji se odnose na rezisera filma
	// watchedNumber mora biti veci od unwatchedNumber
end

query popularDirector()
	watchedDirector();
	// sabiraju se svi ArtistReviewBadge objekti koji se odnose na rezisera filma
	// da bi se uslov zadovoljio, mora biti barem 50% ArtistReviewBadge objekata od ukupnog
	// broja korisnika (ukupan broj korisnika predstavljen globalnom prom)
	// posmatraju se SAMO registrovani korisnici
	// postaviti globalnu promeljivu pri inicijalizaciji sesije (velicina liste svih reg korisnika)
end

query goodDirector()
	popularDirector();
end

rule "Film will be successfull"
    when
    	$m : MessageDto (  );
        goodDirector() and goodScenarist() and goodActors()
    then
    	$m.setMessage("Film will be successfull");
    	$m.setResult("Film will be successfull");
end

rule "Film might be successfull"
    when
    	$m : MessageDto (  );
        goodDirector() or goodScenarist() or goodActors()
    then
    	$m.setMessage("Film might be successfull");
    	$m.setResult("Users like watching some artists in this film, so, this film may be popular.");
end

rule "Film wont be successfull"
    when
    	$m : MessageDto (  );
        not goodDirector() and not goodScenarist() and not goodActors()
    then
    	$m.setMessage("Film wont be successfull");
    	$m.setResult("Neither director nor scenarist nor actors are popular on this platform, so, don't expect too much from this film.");
end
